#!/bin/bash
# Check Stripe webhook configuration

echo "=========================================="
echo "🔍 STRIPE WEBHOOK CONFIGURATION CHECK"
echo "=========================================="
echo ""

cd /opt/llmready/backend

echo "1️⃣ What webhook URL should Stripe call?"
echo ""
echo "Your webhook endpoint should be:"
echo "  https://api.llmready.ai/api/v1/webhooks/stripe"
echo "  (or whatever your production domain is)"
echo ""

echo "2️⃣ Check Stripe Dashboard"
echo ""
echo "Go to: https://dashboard.stripe.com/webhooks"
echo "(Make sure you're in TEST mode if using test keys)"
echo ""
echo "Do you see a webhook endpoint configured?"
echo ""
echo "If YES:"
echo "  - What's the URL?"
echo "  - What's the status? (Enabled/Disabled)"
echo "  - Click on it → View logs → Any recent events?"
echo ""
echo "If NO:"
echo "  You need to create one:"
echo "  1. Click 'Add endpoint'"
echo "  2. Endpoint URL: https://api.llmready.ai/api/v1/webhooks/stripe"
echo "  3. Select events:"
echo "     - checkout.session.completed"
echo "     - customer.subscription.created"
echo "     - customer.subscription.updated"
echo "     - customer.subscription.deleted"
echo "     - invoice.payment_succeeded"
echo "     - invoice.payment_failed"
echo "  4. Copy the webhook signing secret"
echo "  5. Add to .env: STRIPE_WEBHOOK_SECRET=whsec_..."
echo ""

echo "3️⃣ Test webhook endpoint is accessible"
echo ""
echo "From anywhere (your machine), run:"
echo "  curl -X POST https://api.llmready.ai/api/v1/webhooks/stripe"
echo ""
echo "Should return 400 (missing signature) NOT 404 or 500"
echo ""

echo "=========================================="
echo "📝 Report Back"
echo "=========================================="
echo ""
echo "Tell me:"
echo "  1. Is webhook configured in Stripe Dashboard? (Yes/No)"
echo "  2. What URL is configured?"
echo "  3. Is it enabled?"
echo "  4. Can you curl the endpoint and get 400?"
echo "=========================================="